name: jobenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.0.4
  - numpy>=1.20.0
  - pandas>=1.3.0
  - requests>=2.25.0
  - python-dotenv>=0.19.0
  - pydantic>=1.8.0
  - spacy>=3.1.0
  - scikit-learn>=1.0.0
  - pip:
    - sentence-transformers>=2.0.0
    - selenium>=4.1.0
    - webdriver-manager>=3.5.0
    - beautifulsoup4>=4.10.0
    - langchain>=0.0.267  # For agent orchestration
    - fastapi>=0.95.0  # For API creation if needed
    - uvicorn>=0.22.0  # To run FastAPI
    - transformers>=4.30.0  # For more advanced NLP if needed
    - joblib>=1.2.0  # For parallel processing
    - pyyaml>=6.0  # For configuration
    - undetected-chromedriver>=3.5.0  # More robust than standard selenium for LinkedIn