name: jobenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.0.4
  - numpy>=1.20.0
  - pandas>=1.3.0
  - requests>=2.25.0
  - python-dotenv>=0.19.0
  - pydantic>=1.8.0
  - spacy>=3.1.0
  - scikit-learn>=1.0.0
  - watchdog
  - sentence-transformers>=2.0.0
  - selenium>=4.1.0
  - webdriver-manager>=3.5.0
  - beautifulsoup4>=4.10.0
  - fastapi>=0.95.0
  - uvicorn>=0.22.0
  - transformers>=4.30.0
  - joblib>=1.2.0
  - pyyaml>=6.0
  - streamlit==1.22.0
  - openai>=0.27.0
  - faiss-cpu>=1.7.3
  - tiktoken>=0.3.3
  - openpyxl>=3.0.10
  - python-docx>=0.8.11
  - PyPDF2>=1.26.0
  - requests
  - pip:
    - langchain>=0.0.267
    - undetected-chromedriver>=3.5.0
    - chromadb>=0.3.21
    - duckduckgo-search>=0.6.0
    - pdfplumber>=0.7.4
    - langchainhub>=0.0.267